extends: airbnb
parser: babel-eslint
rules:
  comma-dangle:
    - error
    - never
  react/forbid-prop-types:
    - off
  react/prefer-stateless-function:
    - off
  react/prop-types:
    - off
  prefer-arrow-callback:
    - off
